CREATE TABLE pos_device (
    id SERIAL NOT NULL PRIMARY KEY,
    device_id VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    online BOOLEAN NOT NULL,
    provider VARCHAR(255) NOT NULL,
    last_activity TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (device_id, provider)
);
