CREATE TABLE pos_device (
    id BIGINT NOT NULL PRIMARY KEY,
    device_id VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    online BOOLEAN NOT NULL,
    provider VARCHAR(255) NOT NULL,
    last_activity TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
